logging:
  file: ${user.home}/logs/dice-test/price.log
  level.*: INFO
  level.io.terminus: DEBUG

spring:
  application:
    name: dice-test-service

rpc.mode: true

rpc.dubbo:
  module: dice-test-service
  reg-protocol: zookeeper
  registry-address: ${ZOOKEEPER_HOST:127.0.0.1}:${ZOOKEEPER_PORT:2181}
  port: ${DUBBO_PORT:20880}

terminus:
  rocketmq:
    #nameServerAddress: ${ROCKETMQ_NAMESRV_HOST:localhost}:${ROCKETMQ_NAMESRV_PORT:9876}
    nameServerAddress: 30.40.87.32:9876;30.40.87.32:9877
    consumerGroup: dice-test